### ISSUE TITLE
How can I edit this site?

### ISSUE THREAD

**Issue by tekblupace** [caressofsteel/hugo-story#1]
Hi, I really like this theme, but if I use the example site, and try to edit the index.html the site does not change at all. How can this theme be edited.

Kind regards

**Comment by caressofsteel** [comment]
Hi. Any changes to HTML will be reflected on reload. If this isn't happening, it's likely a caching issue. Try clearing your browser cache and also try a different browser for good measure. 

The best way to utilize this theme is to add new or edit the existing partial files in the [_layouts/partials_](https://github.com/caressofsteel/hugo-story/tree/master/layouts/partials) folder and then build it with Hugo and browse the built site in your _publishDir_. The [_layouts/index.html_](https://github.com/caressofsteel/hugo-story/blob/master/layouts/index.html) contains a list of partials to load, and that's where you can add or edit the order of page sections such as Banner, Spotlight, etc.
