### ISSUE TITLE
How to specify my own colorX ? 

### ISSUE THREAD

**Issue by rgarrigue** [caressofsteel/hugo-story#11]
Hi @caressofsteel !

A quick question, how can I easily override the default value for, e.g. color7 ? Or create color8 ?

I'ld like to make this white box transparent

![image](https://user-images.githubusercontent.com/1872031/107222829-b21c7900-6a15-11eb-8744-63ca6f54fc17.png)

It's a spotlight, starting by

```
style: "style5 orient-right content-align-right image-position-left onscroll-image-fade-in bg-light"
id: "contact"
content: |
  <ul class="actions stacked">
    <li>
      <a
        target="_blank"
        href="mailto:REDACTED"
        class="button icon fa-envelope primary"
        >Email</a
      >
    </li>
```

Thanks for the theme !

**Comment by caressofsteel** [comment]
There's no implementation -yet- to specify that in front matter. In the meantine, you can edit or add to the .SCSS files for each partial component (banner, spotlight, etc.) that you're trying to edit.

_E.g._ - `hugo-story\assets\sass\components\_banner.scss`

**Comment by rgarrigue** [comment]
So, got it working somehow : copied theme's `_vars.scss` to /assets/sass/libs/, changed color7 value to rgba(0,0,0,0), all good. I wasted ton off time trying to add a color8, without success.
