### ISSUE TITLE
Customizing the available icons for the items.yml

### ISSUE THREAD

**Issue by pamandrejko** [caressofsteel/hugo-story#17]
Thank you for creating this theme! 

I am trying to figure out if there is any way I could include my own icons on the tiles in the items elements. 

I would like to upload my own icons for these tiles:
![Screen Shot 2022-02-04 at 5 24 21 PM](https://user-images.githubusercontent.com/36892852/152611278-0668f31e-6bf1-49f2-bd31-50795c5b6dfa.png)

I can see they are defined in https://github.com/caressofsteel/hugo-story/blob/master/static/assets/css/fontawesome-all.min.css
But don't really see a way to add new ones to the collection.

**Comment by caressofsteel** [comment]
The icons are FontAwesome glyphs. They are defined as [Base64 data URIs](https://css-tricks.com/data-uris/). You could possibly define your own within the CSS, though I've never tried it. I would probably link to custom icons I created myself or include a new library with the icons I wanted.

Check here for more info:
https://fontawesome.com/v5.15/how-to-use/on-the-desktop/referencing-icons/using-glyphs
