### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by R0quef0rt** [caressofsteel/hugo-story#2]
Hi!

Thanks for porting this beautiful theme. The story we're writing is going to be known across the world, one day.

Would you be able to tell me the best way to customize the font? I've spent an embarrassing amount of time trying to figure it out, with no luck. 

I'm not a very strong developer, but if you can point me in the right direction, I can probably figure the rest out.

Thanks in advance for any help you can provide.

Ink

**Comment by caressofsteel** [comment]
Hi Ink,

Thanks and you're welcome. Most of the visual changes can be made in the SASS files. Have a look at the font setting in the _[assets/sass/main.scss](https://github.com/caressofsteel/hugo-story/blob/master/assets/sass/main.scss)_ file. 

You'll need to regenerate the site after making changes.

**Comment by JPCodaLot** [comment]
For anyone wanting to change the font family in the future:

You can set the font details in the `themes/hugo-story/assets/sass/libs/_vars.scss` file under the section named `Font`. If you want to use a font family from [Google Fonts](https://fonts.google.com/), add the following to the `themes/hugo-story/assets/sass/main.scss` file:

```scss
@import url('https://fonts.googleapis.com/css?family=Your+Font+Family');
```

*Don't forget to regenerate the site after making your changes.*
