### ISSUE TITLE
How to add pages?

### ISSUE THREAD

**Issue by AntoineSoetewey** [caressofsteel/hugo-story#23]
Hello,

Thanks for this great theme!

I manage to build a first version with your theme (see the [website](https://elsaetantoine.com/) and the [repo](https://github.com/AntoineSoetewey/elsaetantoine)), but I struggle to add pages for more content.

I tried the following:

- add simple.html file in the [layouts/_default folder](https://github.com/AntoineSoetewey/elsaetantoine/tree/master/layouts/_default)
- add some .md pages in the [content folder](https://github.com/AntoineSoetewey/elsaetantoine/tree/master/content) with the simple layout

but the pages do not look good, see for instance https://elsaetantoine.com/programme/

Could you please tell me what is the best way to edit the layout so that these pages look better? The home page is fine.

Thanks in advance!

**Comment by caressofsteel** [comment]
I suggest [creating and referencing partials](https://github.com/caressofsteel/hugo-story/blob/master/layouts/partials/banner.html) with the proper element and CSS syntax that your page is missing.

**Comment by AntoineSoetewey** [comment]
Thanks for your reply.

Sorry I’m not a programmer so I don’t really understand what I have to do with the banner.html file.

I copied the code of the file in my simple.html file but that doesn’t really solve my problem. Do I have to add it somewhere else ?

Am I the only one who uses your theme and needs to add pages ? If not, could you perhaps redirect me their repositories so I can try to replicate what they have done?

Thanks again for your help.

**Comment by caressofsteel** [comment]
I suggest first going through some good Hugo tutorials to get the basics down and learn how the system works. You should then visit the Hugo repository. There are hundreds of examples of how to implement partials and other elements.
