### ISSUE TITLE
Gallery content behavior different depending on case of file

### ISSUE THREAD

**Issue by Modusmundi** [caressofsteel/hugo-story#25]
Consider the first example:

title: "pics"
style: "style1 big lightbox onscroll-fade-in"
content: |
  all of these pics are factual and would never be edited. you mean people would just lie on the internet?
pictures:
  - title: "facts"
    content: "feelings?"
    thumb: "images/gallery/thumbs/oiled_thumb.png"
    image: "images/gallery/fulls/oiled.png"
    button: "click"

This brings the image in question to the forefront, leaving the site in the background.
	
title: "pics"
style: "style1 big lightbox onscroll-fade-in"
content: |
  all of these pics are factual and would never be edited. you mean people would just lie on the internet?
pictures:
  - title: "facts"
    content: "feelings?"
    thumb: "images/gallery/thumbs/oiled_thumb.png"
    image: "images/gallery/fulls/oiled.PNG"
    button: "click"
    
This opens the image in a new page, losing continuity.

**Comment by caressofsteel** [comment]
Thanks for the report. This appears to be a Hugo behavior, and not a theme issue, so there may be a remedy for it. I know there are configuration settings to handle upper/lower case issues with paths. I would inquire about it in one of the Hugo discussion boards.
