### ISSUE TITLE
question: create a second page?

### ISSUE THREAD

**Issue by camilomarquez** [caressofsteel/hugo-story#3]
Hi all,

Thanks for porting this beautiful theme!
it's possible make to second page with only blog notes for example(or with just a form)?
i try make it in static folder but i cannot get it 
Thanks in advance for any help you can provide.

Camilo

**Comment by caressofsteel** [comment]
Hi Camilo,

You're welcome. You can make as many pages as you like. Just clone one of the existing pages in the theme folder and regenerate the site. If you're not familiar with that process, study Hugo and how it works.

-DR

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by camilomarquez** [comment]
Sorry my bad English, I did not explain you well.
Here is the live example, if u click on "learn on" in sismica section:
https://geofisica.netlify.app/#sismica 
u will go to -> https://geofisica.netlify.app/sismica_full
but the css style its not being applied.
What is wrong? its bc this is a "one page theme"?
Ty @caressofsteel

**Comment by caressofsteel** [comment]
> Sorry my bad English, I did not explain you well.
Here is the live example, if u click on "learn on" in sismica section:
but the css style its not being applied.
What is wrong? its bc this is a "one page theme"?

No, you can create any type of page with whatever content you like with this theme using some or all of the available styles and components. The CSS appears to be loading fine and returning "Status 200 OK" on both the main and other page you sent. The styled typography and images are also appearing, so I'm not sure what you're not seeing. Attach a screenshot of what you should be seeing and we'll sort it out.
