### ISSUE TITLE
changing background color for site

### ISSUE THREAD

**Issue by ghost** [caressofsteel/hugo-story#32]
Hi. How would one achieve "dark mode"? I imagine there is a simple color adjustment to be made somewhere, but do not know where. Can you point me in the right direction?

**Comment by caressofsteel** [comment]
Take a look at the 'scheme' variable. You can see an example on the main page of the theme. The theme doesn't have a "dark mode" toggle, but it could be implemented with a little work. I'd read up on it [HERE](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/). Good luck!

**Comment by amestrack** [comment]
Thanks! In fact, I did not even think of a toggle feature - 'scheme' will do for now, but that link is helpful. This is a great theme and I'm excited to get all the little tweaks dialed in for my site.
