### ISSUE TITLE
Lightbox behavior upon opening

### ISSUE THREAD

**Issue by Dearvoilas** [caressofsteel/hugo-story#35]
Hi,
I'm new to all this; thanks in advance for your help. 

Unsure if something is missing on my side.

Lightbox works fine : 1) Image is loading and 2) fills the screen upon clicking.

The problem I see with the Lightbox is that there is no exit other than by clicking the back button once triggered...

Thanks.

**Comment by caressofsteel** [comment]
Check the Gallery in the demo site. There should be an X allowing you to close the image. Perhaps you've missed something in your implementation?

**Comment by Dearvoilas** [comment]
Thanks!
