### ISSUE TITLE
background-image and new tab history tiles

### ISSUE THREAD

**Issue by egLanghaus** [caressofsteel/hugo-story#36]
I am having a hard time finding where to change this. The effect it has is to present, in some browsers, the default image of that cliff landscape photo as the tile in the browsing history section of a new tab (that hasn't navigated somewhere yet).

This is despite successful changes to other image files having the effect of replacing the favicon - the favicon my site presents is *now* my own (coincidentally similar-looking) image. But still in some browsers the image tile in the history section of a newly opened tab is the old cliff image - anyone have any ideas?

**Comment by egLanghaus** [comment]
Thanks! It is great that you are still active in these 'issues'. I have not confirmed it yet, but I think that clearing the cache works. Probably it is time for me to learn the relevant languages properly and rebuild the site as I see it in my head. Thanks again, Martin

**Comment by caressofsteel** [comment]
@egLanghaus You're welcome. Enjoy the theme.
