### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by pgrunm** [caressofsteel/hugo-story#37]
Hello,

I'm trying to use your Hugo theme to adapt to multiple languages. Is there any way to add multi language support?

Thank you! :)

**Comment by caressofsteel** [comment]
Hugo supports this. Have a look at [Multilingual Mode](https://gohugo.io/content-management/multilingual/).

**Comment by pgrunm** [comment]
Yes, I know. But I wasn't sure about the theme and tried it myself. Maybe there was a guide or something.

**Comment by programLyrique** [comment]
@pgrunm did you manage to use this theme with multiple languages?
