### ISSUE TITLE
Disable Page Load Animation

### ISSUE THREAD

**Issue by mikurindotc** [caressofsteel/hugo-story#39]
Is there any way to disable the animation that plays on load? It is breaking my image logo on the banner.

**Comment by caressofsteel** [comment]
When reporting bugs, please be as specific as possible. I assume you're referencing the fade of the image? That can be changed or disabled by editing the CSS.

**Comment by mikurindotc** [comment]
Sorry.

It's not the fade. I've created a "logo" class with top: 10% but when the page is loading, the banner gets on top of the text, and when the animation ends, it pops to where it should be.

![image](https://user-images.githubusercontent.com/55168579/215547621-3638b505-807d-4378-ad9c-5a3c9df2aeac.png)
![image](https://user-images.githubusercontent.com/55168579/215547637-840b8aec-3203-4c38-bcab-8b920e51d207.png)

Like this /\

**Comment by caressofsteel** [comment]
This appears to be an error with your implementation, not an issue with the theme itself. The only advice I can give is to put in some time to study how the theme is structured and how SCSS and other parts work.
