### ISSUE TITLE
question: create FIRST page? (eg Hello World)

### ISSUE THREAD

**Issue by jpwynn** [caressofsteel/hugo-story#4]
Fairly techy guy, but _total noob_ re Hugo... trying Hugo (using your theme) for the first time. (Second time actually, the Hugo getting started docs using the Ananke theme went perfectly, no errors about missing templates.)

For starters, is the correct git url: https://github.com/caressofsteel/hugo-story.git ? Eg it is properly installed using: 
```
git submodule add https://github.com/caressofsteel/hugo-story.git themes/story
```

Is there _anywhere_ a guide to populating a "hello world" site using your theme? Ideally a guide to replicating your demo site with a banner, some spotlights, etc? 

I cannot tell if it was installed wrong, or if some sort of manual template-creation step is needed to use this theme?

Although not  a blog theme, I tried anyway, just to have at least some content: `hugo new posts/my-first-post.md` 

Then based on the element names in your demo site, just shooting in the dark, I also tried `hugo new banner/my-first-banner.md` and `hugo new spotlight/my-first-spotlight.md`

Trying `hugo server -D` yields:

```
WARN 2020/08/30 10:15:14 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/08/30 10:15:14 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/08/30 10:15:14 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/08/30 10:15:14 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/08/30 10:15:14 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/08/30 10:15:14 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/08/30 10:15:14 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2020/08/30 10:15:14 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
ERROR 2020/08/30 10:15:14 TOCSS: failed to transform "noscript.scss" (text/x-scss): resource "scss/sass/noscript.scss_2103917ee0aa183caf6c7ba1cd5fe1e6" not found in file cache
```

I'm using the Mac precompiled binary (64 bit), which AFAIK includes the sass support... at least the referenced Hugo install page makes no mention of anything special needed for `tags extended` for the Mac binary.

_Seems_ like installed ok:
```
ls -a themes/story
.		.git		README.md	exampleSite	layouts		theme.toml
..		LICENSE		assets		images		static
```

and 
```
ls -a themes/story/layouts/partials/template
.		..		favicon.html	footer.html	head.html	scripts.html
```

**Comment by jpwynn** [comment]
Just as an aside, some themes toss a helpful little bone to users in the form of sections of the readme called `Get the theme` and `Preview the theme` and `Add content:Introduction section` and `Add content:Home page` and 'Add content: Projects section` and `Add content: Blog section`

Excellent example:  https://github.com/victoriadrake/hugo-theme-introduction

Happy to write those sections for your Readme once I figure out how to use Story.

**Comment by caressofsteel** [comment]
Hi @jpwynn, This theme is far from taking full advantage of what Hugo has to offer. I do have plans to make it so, but I have not had the time to do it myself.  I think what you're running into with the command line errors is there are no templates defined that reference the theme's partials. 

To create a new home page create a new layouts/index.html and include whatever partials (new or existing) that you want to use and then regenerate the site. You can also try creating a _default folder in the layouts folder and creating a page called spotlight.html. Inside spotlight.html, construct the template code that calls the spotlight partial. 

If you look at the structure of the Ananke theme, you can see examples of the _default templates and you an also see what's not currently implemented in HugoStory. I welcome any effort to make this theme more compatible with the Hugo feature set, and using a theme like Ananke would be a great example of pull from in doing so.

**Comment by menzert** [comment]
Hi @jpwynnm, in order to get this theme up and running with the included exampleSite, just follow these steps:

1. create a new site:
hugo new site story-examplesite

2. clone this git repository
cd .\story-examplesite\
git clone https://github.com/caressofsteel/hugo-story.git ./themes/hugo-story

3. copy the exampleSite included in this repository
cp ./themes/hugo-story/exampleSite/* ./static/

4. copy the config.toml from default to the main directory
cp ./themes/hugo-story/exampleSite/config/default/config.toml ./

5. run the exampleSite (drafts included)
hugo server -D

6. View the exampleSite in your browser
//localhost:1313/

Hope this helps.
I am also trying to adapt this theme for my personal needs... :-)

**Comment by menzert** [comment]
7. move the index.* files to the layouts-folder:
mv ./static/index.* ./layouts/

Now you can edit the index.html and see the effect in your browser.

**Comment by caressofsteel** [comment]
Thanks for writing up these steps @menzert. I'll make a note to run through them and update the docs.

**Comment by NumerousHats** [comment]
That was very helpful @menzert, thanks!

However, just in case anybody unfamiliar with the command line comes across this, here are a few typo fixes:

> 
>     2. clone this git repository
>        cd .\story-examplesite

that should be `cd ./story-examplesite`

>     3. copy the exampleSite included in this repository
>        cp ./themes/hugo-story/exampleSite/* ./static/

I'm pretty sure you meant `cp -r ./themes/hugo-story/exampleSite/* ./static/`, yes? Otherwise the subdirectories don't get copied.

**Comment by menzert** [comment]
Thanks, @NumerousHats, you're absolutley right! I've corrected my initial comment. Thumbs up for that!

**Comment by caressofsteel** [comment]
These issues are addressed in code contributed by @applikationsprogramvara.

**Comment by AntoineSoetewey** [comment]
I came across this issue on how to add a page. I see that it has been closed, perhaps anyone may help for this [issue](https://github.com/caressofsteel/hugo-story/issues/23) since it is also about how to add more pages?
