### ISSUE TITLE
Favicon Generation

### ISSUE THREAD

**Issue by esologic** [caressofsteel/hugo-story#46]
Hello! Are users responsible for creating the set of favicons or is this something hugo can do for us? I'm talking about the:
* android-chrome-192x192.png
* android-chrome-512x512.png
* apple-touch-icon.png
* browserconfig.xml
* favicon.ico
* favicon-16x16.png
* favicon-32x32.png
* mstile-150x150.png
* safari-pinned-tab.svg
* site.webmanifest

Looking at the sample `production/config.toml`, providing a path to a logo with:

```
[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true
```

Suggests to me that maybe hugo can make the files, but I'm not sure.

**Comment by caressofsteel** [comment]
You create all of these assets using a different tool. Most favicon generators will produce all of these files for you.
